### ISSUE TITLE
生成证书需要域名

### ISSUE THREAD

**Issue by xiaofeihe** [Bluek404/Stepladder#5]
你好买的gce 服务器没有 域名， 只有IP地址
我应该怎么生产证书，我直接用IP 会出现下面问题 

cannot validate certificate for 104.155.×.× because it doesn't contain any IP SANs

我随意写了一个域名然后在我电脑的hosts 修改 域名指向 还是包类似错误。

**Comment by Bluek404** [comment]
随意的域名添加到hosts的话是可以使用的
证书和配置文件里是否也使用的相同域名？

也可以去申请一个免费的.tk域名

**Comment by kekek** [comment]
嗯，我有域名，也出现这个错误了，现在不知懂怎么整，linode vps

**Comment by Bluek404** [comment]
@kekek 配置文件和生成证书时的CN是怎么写的？（不用给出key）

**Comment by kekek** [comment]
非常感谢Bluek404 大哥的提点，问题已解决。

正是配置文件client.ini和证书中的CN不同造成的，在把host改为CN中相同的域名后，就可以了。

下面是我的错误配置：
======================CN======================
Common Name (eg, your name or your server's hostname) []:www.vovol.net
======================server.ini======================
 [client]
#验证身份用的密钥
key = xxxxxxx
[server]
#服务器监听端口
port = 8081
======================client.ini======================
[client]
#验证身份用的密钥
key =xxxxxxx
#本地监听端口
port = 7071
[server]
#服务器地址
host =106.185.26.204 
#服务器端口
port = 8081
