### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by xiaofeihe** [Bluek404/Stepladder#6]
我在阿里云上运行 Stepladder 客户端，运行 1,2天后 出现 cpu 100% 情况（没有浏览器访问的时候）
如果有 浏览器使用 Stepladder 客户端  会经常出现2个cpu 100% 情况。

截图：http://ww1.sinaimg.cn/large/6637bd6cgw1ep4ky7r60ej21hc0u0e81.jpg

我在国外有个服务器，运行Stepladder 服务端， 但是国内 歌华，或者宽带通100M 宽带都不能看 youtube 720P 视频，  后来 发现 在阿里云安装 客户端 ，浏览器直接 socket 指向阿里云的端口 可以看 1080 P的视频 几乎没有卡的现象。
 我就在 阿里云上长期运行 Stepladder ，结果第二天 就出现网速下降，反映慢，等了阿里云看了一下 cpu 100%

经过测试 重新启动客户端后cpu  几乎没有消耗。 运行几分钟后 cpu 就高了

**Comment by Bluek404** [comment]
啊哈总算有人发现这个BUG了

其实我上个月就发现了，但是一直没找到重现方法

BUG特征是占满一个核心的CPU使用率

然后貌似是看视频之类的才会触发

但是我本地无法重现（从发布以来这个BUG我只遇到2次）

能不能帮忙测试一下具体干些什么才会触发？

比如打开了什么网站

**Comment by xiaofeihe** [comment]
就是看youtube 视频就会出现这个问题，几分钟就会重现。

服务器 环境为： 阿里：4核CPU ，4G 内存 ，debian 7 系统。

**Comment by xiaofeihe** [comment]
好像升级最近可以了，没有出现100% 的现象了。

**Comment by Bluek404** [comment]
@xiaofeihe 那看来就是socks5协议的问题了

多谢反馈
