### ISSUE TITLE
同公网IP下不能使用多个客户端

### ISSUE THREAD

**Issue by brainbush** [Bluek404/Stepladder#7]

**Comment by Bluek404** [comment]
和时间有关系？

请检查网络环境

**Comment by brainbush** [comment]
经测试发现，当局域网内有一台计算机运行stepladder后，另一台电脑将无法连接到服务器，提示错误！

**Comment by Bluek404** [comment]
解决方案：服务端使用`session`来代替现有的使用`IP`识别客户端

如果有这个需求的用户多的话可能会使用上面的方案

不过既然用的一个IP（一般是在内网中），我更推荐直接使用内网ip连接已运行的stepladder客户端

**Comment by wfjsw** [comment]
当然要多重登陆啦 不然做出手机APP和电脑冲突怎么破

**Comment by Bluek404** [comment]
@wfjsw 这种情况更推荐直接使用电脑的代理

减少不必要的资源占用

**Comment by wfjsw** [comment]
→_→主要想做个类似shadowsocks for android那样的
已经找人做了w

**Comment by Bluek404** [comment]
最终没有直接使用session
而是加了个单IP客户端计数

**Comment by wfjsw** [comment]
嗯等一个小时左右ci更新
